name: "Build Nix package on Ubuntu"

on:
  push:
    paths:
      - src/**
      - .github/workflows/build_nix.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v31

      - name: Building package
        run: nix build 
