name: "Build legacy Nix package on Ubuntu"

on:
  push:
    paths:
      - src/**
      - .github/workflows/build_nix.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v26
      - name: Building package
        run: nix build 
